config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'

  # 会員関連のルーティング(deviseの不要なルーティングはskipで飛ばしている)
  devise_for :groups, skip: [:passwords], controllers: {
    sessions: 'groups/sessions',
    registrations: 'groups/registrations'
  }
  devise_for :residents, skip: [:passwords], controllers: {
    sessions: 'residents/sessions',
    registrations: 'residents/registrations'
  }
  # 会員から他の会員の詳細ページなどは見れなくてもいいのでresourceで実装
  resource :resident, only: %i[edit show update]
  patch 'resident/withdrawal' => 'residents#withdrawal', as: 'resident_withdrawal'

  resource :group, only: %i[edit show update]
  patch 'group/withdrawal' => 'groups#withdrawal', as: 'group_withdrawal'
  get 'groups/index' => 'groups#index', as: 'groups'

  # 投稿機能のためのルーティング
  resources :cats do
    resources :comments, only: %i[create destroy]
  end

  # 対応機能のためのルーティング
  resources :handles, only: [:edit, :update]
  patch 'handles/:id/status' => 'handles#status', as: 'handle_status'
  patch 'handles/:id/failed' => 'handles#failed', as: 'handle_failed'

  # 通知機能ためのルーティング
  resources :notices, only: [:index, :update]

  # 検索のためのルーティング
  get '/searchs/cats' => 'searchs#cats', as: 'search_cats'
  post '/searchs/groups' => 'searchs#groups', as: 'search_groups'
  post '/searchs/group_cats' => 'searchs#group_cats', as: 'search_group_cats'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :cat
  belongs_to :group, optional: true
  belongs_to :resident, optional: true
  # 通知用アソシエーション
  has_many :notices, dependent: :destroy

  # バリデーション
  with_options presence: true do
    validates :cat_id
    validates :comment,     length: { maximum: 500 }
     # 条件分岐によるバリデーション（コメントが保護団体か住民かを分けるためのバリデーション）
    validates :resident_id, if: -> { group_id.blank? }
    validates :group_id,    if: -> { resident_id.blank? }
  end

  # residentが投稿にコメントした時
  def send_resident_comment(resident_send_id, group_receive_id)
    notification = Resident.find(resident_send_id).active_notifications.new(
      comment_id: id,
      resident_send_id: resident_send_id,
      group_receive_id: group_receive_id
      )
    notification.save if notification.valid?
  end

  # groupが投稿にコメントした時
  def send_group_comment(group_send_id, resident_receive_id)
    notification = Group.find(group_send_id).active_notifications.new(
      comment_id: id,
      group_send_id: group_send_id,
      resident_receive_id: resident_receive_id
      )
    notification.save if notification.valid?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # コメントの通知を取得するためのメソッド（全てのビューで使用するため）
  before_action :notice_index
  # 通知テーブルのオブジェクトも同時に作成する
  def create
    comment = Comment.new(comment_params)
    comment.cat_id = params[:cat_id]
    comment.save
    # 通知テーブルのレコード作成
    unless comment.resident_id == nil
      # コメント者がresidentの場合
      group_receive_id = Cat.find(params[:cat_id]).handle.group_id
      comment.send_resident_comment(comment.resident_id, group_receive_id)
    else
      # コメント者がgroupの場合
      resident_receive_id = Cat.find(params[:cat_id]).resident_id
      comment.send_group_comment(comment.group_id, resident_receive_id)
    end
    # 非同期通信用の変数定義
    @cat = Cat.find(params[:cat_id])
    @comments = Cat.find(params[:cat_id]).comments
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    # 非同期通信用の変数定義
    @cat = Cat.find(params[:cat_id])
    @comments = Cat.find(params[:cat_id]).comments
  end

  private
  def comment_params
    params.require(:comment).permit(:group_id, :resident_id, :comment)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<% if resident_signed_in? %>
  <%= form_with model: comment, url: cat_comments_path(cat), remote:true do |f| %>
    <%= f.hidden_field :resident_id, value: current_resident.id %>
    <div class="form-row">
      <div class="col-10">
        <%= f.text_area :comment, class: "form-control", placeholder: "コメント" %>
      </div>
      <div class="col-2 d-flex align-items-end">
        <%= f.submit '投稿', class: "btn btn-primary w-100" %>
      </div>
    </div>
  <% end %>
<% elsif group_signed_in? %>
  <%= form_with model: comment, url: cat_comments_path(cat), remote:true do |f| %>
    <%= f.hidden_field :group_id, value: current_group.id %>
    <div class="form-row">
      <div class="col-10">
        <%= f.text_area :comment, class: "form-control", placeholder: "コメント" %>
      </div>
      <div class="col-2 d-flex align-items-end">
        <%= f.submit '投稿', class: "btn btn-primary w-100" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/comments/_index.html.erb
<div class="container">
  <% comments.reverse_each do |comment| %>
    <% if comment.resident_id.present? %>
      <div class="row resident-comment align-items-center border-bottom">
      <div class="col-2 text-center pt-2">
        <h2 class="fas fa-user text-black-50"></h2>
      </div>
      <div class="col-6 comment-detail text-break p-2">
      <div>
        <%= comment.comment %>
      </div>
      <div class="text-left text-black-50">
        <span><%= comment.created_at.to_s(:datetime) %></span>
      </div>
      </div>
      <div class="col-2 offset-md-2">
          <% if resident_signed_in? %>
            <% if comment.resident_id == current_resident.id %>
              <%= link_to '削除', cat_comment_path(cat, comment), method: :delete, remote:true, class: "btn btn-sm btn-danger float-right" %>
            <% end %>
          <% elsif group_signed_in? %>
            <% if comment.group_id == current_group.id %>
              <%= link_to '削除', cat_comment_path(cat, comment), method: :delete, remote:true, class: "btn btn-sm btn-danger float-left" %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="row group-comment align-items-center border-bottom">
        <div class="col-2">
          <% if resident_signed_in? %>
            <% if comment.resident_id == current_resident.id %>
              <%= link_to '削除', cat_comment_path(cat, comment), method: :delete, remote:true, class: "btn btn-sm btn-danger float-right" %>
            <% end %>
          <% elsif group_signed_in? %>
            <% if comment.group_id == current_group.id %>
              <%= link_to '削除', cat_comment_path(cat, comment), method: :delete, remote:true, class: "btn btn-sm btn-danger float-left" %>
            <% end %>
          <% end %>
        </div>
        <div class="col-6 offset-md-2 comment-detail text-break p-2 text-left">
          <%= comment.comment %>
          <div class="text-right text-black-50">
            <span><%= comment.created_at.to_s(:datetime) %></span>
          </div>
        </div>
        <div class="col-2 text-center pt-2">
          <h2 class="fas fa-users text-black-50"></h2>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#comment').html("<%= j(render partial: '/comments/index', locals: {comments: @comments, cat: @cat}) %>");
$("#comment_comment").val("");

app/views/comments/destroy.js.erb
$('#comment').html("<%= j(render partial: '/comments/index', locals: {comments: @comments, cat: @cat}) %>");