config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'

  # 会員関連のルーティング(deviseの不要なルーティングはskipで飛ばしている)
  devise_for :groups, skip: [:passwords], controllers: {
    sessions: 'groups/sessions',
    registrations: 'groups/registrations'
  }
  devise_for :residents, skip: [:passwords], controllers: {
    sessions: 'residents/sessions',
    registrations: 'residents/registrations'
  }
  # 会員から他の会員の詳細ページなどは見れなくてもいいのでresourceで実装
  resource :resident, only: %i[edit show update]
  patch 'resident/withdrawal' => 'residents#withdrawal', as: 'resident_withdrawal'

  resource :group, only: %i[edit show update]
  patch 'group/withdrawal' => 'groups#withdrawal', as: 'group_withdrawal'
  get 'groups/index' => 'groups#index', as: 'groups'

  # 投稿機能のためのルーティング
  resources :cats do
    resources :comments, only: %i[create destroy]
  end

  # 対応機能のためのルーティング
  resources :handles, only: [:edit, :update]
  patch 'handles/:id/status' => 'handles#status', as: 'handle_status'
  patch 'handles/:id/failed' => 'handles#failed', as: 'handle_failed'

  # 通知機能ためのルーティング
  resources :notices, only: [:index, :update]

  # 検索のためのルーティング
  get '/searchs/cats' => 'searchs#cats', as: 'search_cats'
  post '/searchs/groups' => 'searchs#groups', as: 'search_groups'
  post '/searchs/group_cats' => 'searchs#group_cats', as: 'search_group_cats'
end

app/models/resident.rb
class Resident < ApplicationRecord
  # アソシエーション
  has_many :cats, dependent: :destroy
  has_many :comments, dependent: :destroy
  # 通知機能用のアソシエーション
  # 自分からの通知
  has_many :active_notifications, class_name: 'Notice', foreign_key: 'resident_send_id', dependent: :destroy
  # 相手からの通知
  has_many :passive_notifications, class_name: 'Notice', foreign_key: 'resident_receive_id', dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # バリデーション
  # 郵便番号の正規表現（ハイフンなし7桁）
  VALID_POSTAL_CODE_REGIX = /\A\d{7}\z/

  with_options presence: true do
    validates :name
    validates :postal_code
    validates :address
  end

  validates :postal_code, format: { with: VALID_POSTAL_CODE_REGIX}, allow_blank: true

  # boolean型のバリデーション
  validates :withdrawal,    inclusion: { in: [true, false] }

  # geocoderで住所カラムから経度・緯度に変換し保存するための記述
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/controllers/residents/confirmations_controller.rb
# frozen_string_literal: true

class Residents::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/residents/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Residents::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/residents/passwords_controller.rb
# frozen_string_literal: true

class Residents::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/residents/registrations_controller.rb
# frozen_string_literal: true

class Residents::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/residents/sessions_controller.rb
# frozen_string_literal: true

class Residents::SessionsController < Devise::SessionsController

  # 退会後の住民ユーザーのログイン制限
  before_action :reject_inactive_resident, only: [:create]

  # 退会済みユーザーを判別しredirectを設定
  def reject_inactive_resident
    @resident = Resident.find_by(email: params[:resident][:email])
    # 上記コードでemailカラムを用いて検索、下記コードは格納されていればtrue、いなければnull
    if @resident
      # 下記コードは　passwordが適切　かつ(&&)　@group.withdrawalがtrue　であればredirect_toが走る処理
      if @resident.valid_password?(params[:resident][:password]) && @resident.withdrawal
        redirect_to new_resident_session_path
      end
    end
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/residents/unlocks_controller.rb
# frozen_string_literal: true

class Residents::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/residents_controller.rb
class ResidentsController < ApplicationController
  # ログイン前のアクション制限
  before_action :authenticate_resident!
  
  # コメントの通知を取得するためのメソッド（全てのビューで使用するため）
  before_action :notice_index

  def show
    @cats = Cat.where(resident_id: current_resident.id)
  end

  def edit
    @resident = current_resident
  end

  def update
    @resident = current_resident
    if @resident.update(resident_params)
      redirect_to resident_path(current_resident)
    else
      render :edit
    end
  end

  # 退会機能
  def withdrawal
    resident = current_resident
    resident.update(withdrawal: true)
    reset_session
    redirect_to root_path
  end

  # ストロングパラーメータ
  def resident_params
    params.require(:resident).permit(:name, :email, :postal_code, :address)
  end
end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/views/residents/edit.html.erb
<div class="container-fluid">
  <div class="row justify-content-center align-items-center" style="height: calc(100vh - 76px);">
     <%= form_with model: @resident, url: resident_path, class: "form-signup", local: true do |f| %>
      <div class="field mb-4 text-center">
        <%= image_tag 'logo.png', :size => '100x100' %>
      </div>
      <div class="field mb-2">
        <p class="fas fa-paw">名前</p>
        <%= f.text_field :name, autofocus: true, class: "form-control" %>
        <%= render "/layouts/error_messages", model: @resident, attribute: :name %>
      </div>
      <div class="field mb-2">
        <p class="fas fa-paw">メールアドレス</p>
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
        <%= render "/layouts/error_messages", model: @resident, attribute: :email %>
      </div>
      <div class="field mb-2">
        <p class="fas fa-paw">郵便番号（ハイフンなし）</p>
        <%= f.text_field :postal_code, class: "form-control" %>
        <%= render "/layouts/error_messages", model: @resident, attribute: :postal_code %>
      </div>
      <div class="field mb-2">
        <p class="fas fa-paw">住所</p>
        <%= f.text_area :address, class: "form-control" %>
        <%= render "/layouts/error_messages", model: @resident, attribute: :address %>
      </div>
      <div class="actions text-center">
        <%= f.submit "編集", class: "btn btn-secondary btn-block" %>
      </div>
      <div class="text-right mt-2">
        <%= link_to '退会', resident_withdrawal_path, method: :patch, "data-confirm"=>"本当に退会しますか？" %>
        </div>
    <% end %>
  </div>
</div>

app/views/residents/show.html.erb
<div class="col-3 bg-light sidebar overflow-auto">
  <%= render "/cats/sideindex/", cats: @cats %>
</div>

<div class="show col-9">
  <div class="container mt-5">
    <div class="row">
      <div class="col-10 offset-md-1">
        <h1 class="fas fa-address-card"></h1>
        <table class="table mt-5">
          <tbody>
            <tr>
              <th>名前</th>
              <td><%= current_resident.name %></td>
            </tr>
            <tr>
              <th>メールアドレス</th>
              <td><%= current_resident.email %></td>
            </tr>
            <tr>
              <th>郵便番号</th>
              <td>〒<%= current_resident.postal_code %></td>
            </tr>
            <tr>
              <th>住所</th>
              <td><%= current_resident.address %></td>
            </tr>
          </tbody>
        </table>
        <div class="text-right">
          <%= link_to '編集', edit_resident_path, class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>