config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'

  # 会員関連のルーティング(deviseの不要なルーティングはskipで飛ばしている)
  devise_for :groups, skip: [:passwords], controllers: {
    sessions: 'groups/sessions',
    registrations: 'groups/registrations'
  }
  devise_for :residents, skip: [:passwords], controllers: {
    sessions: 'residents/sessions',
    registrations: 'residents/registrations'
  }
  # 会員から他の会員の詳細ページなどは見れなくてもいいのでresourceで実装
  resource :resident, only: %i[edit show update]
  patch 'resident/withdrawal' => 'residents#withdrawal', as: 'resident_withdrawal'

  resource :group, only: %i[edit show update]
  patch 'group/withdrawal' => 'groups#withdrawal', as: 'group_withdrawal'
  get 'groups/index' => 'groups#index', as: 'groups'

  # 投稿機能のためのルーティング
  resources :cats do
    resources :comments, only: %i[create destroy]
  end

  # 対応機能のためのルーティング
  resources :handles, only: [:edit, :update]
  patch 'handles/:id/status' => 'handles#status', as: 'handle_status'
  patch 'handles/:id/failed' => 'handles#failed', as: 'handle_failed'

  # 通知機能ためのルーティング
  resources :notices, only: [:index, :update]

  # 検索のためのルーティング
  get '/searchs/cats' => 'searchs#cats', as: 'search_cats'
  post '/searchs/groups' => 'searchs#groups', as: 'search_groups'
  post '/searchs/group_cats' => 'searchs#group_cats', as: 'search_group_cats'
end

app/views/layouts/header/_before.html.erb
<nav class="col-12 px-4 navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand ml-5" href="/"><%= image_tag 'logo.png', :size => '50x50' %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto mr-5">
      <li class="nav-item">
        <%= link_to '保護団体', groups_path, class: "nav-link fas fa-users" %>
      </li>
       <li class="nav-item">
        <%= link_to 'マップ', cats_path, class: "nav-link fas fa-paw" %>
      </li>
       <li class="nav-item">
        <%= link_to 'ログイン', new_resident_session_path, class: "nav-link fas fa-sign-in-alt" %>
      </li>
      <li class="nav-item">
        <%= link_to '登録', new_resident_registration_path, class: "nav-link fas fa-user-plus" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/header/_group.html.erb
<nav class="col-12 px-4 navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/"><%= image_tag 'logo.png', :size => '50x50' %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'マイページ', group_path, class: "nav-link fas fa-address-card" %>
      </li>
      <li class="nav-item">
        <%= link_to '保護団体', groups_path, class: "nav-link fas fa-users" %>
      </li>
       <li class="nav-item">
        <%= link_to 'マップ', cats_path, class: "nav-link fas fa-paw" %>
      </li>
       <li class="nav-item">
        <%= link_to 'ログアウト', destroy_group_session_path, method: :delete, class: "nav-link fas fa-sign-out-alt" %>
      </li>
      <li class="nav-item">
        <a data-toggle="modal" href="#exampleModalLong" class="fas fa-bell nav-link text-black-50" >通知</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/header/_resident.html.erb
<nav class="col-12 px-4 navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/"><%= image_tag 'logo.png', :size => '50x50' %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to '依頼', new_cat_path, class: "nav-link fas fa-external-link-alt" %>
      </li>
      <li class="nav-item">
        <%= link_to 'マイページ', resident_path, class: "nav-link fas fa-address-card" %>
      </li>
      <li class="nav-item">
        <%= link_to '保護団体', groups_path, class: "nav-link fas fa-users" %>
      </li>
       <li class="nav-item">
        <%= link_to 'マップ', cats_path, class: "nav-link fas fa-paw" %>
      </li>
       <li class="nav-item">
        <%= link_to 'ログアウト', destroy_resident_session_path, method: :delete, class: "nav-link fas fa-sign-out-alt" %>
      </li>
      <li class="nav-item">
        <a data-toggle="modal" href="#exampleModalLong" class="fas fa-bell nav-link text-black-50" >通知</a>
      </li>
    </ul>
  </div>
</nav>